name: Deploy Pokedex

on:
  push:
    branches: [main]
  pull_request:
    branches: [main]

jobs:
  test-and-deploy:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v3

      - name: Setup Node.js
        uses: actions/setup-node@v3
        with:
          node-version: '18'
          cache: 'npm'

      - name: Install Backend Dependencies
        run: npm install

      - name: Start API Server
        env:
          NODE_ENV: test
          PORT: 3000
          HOST: 0.0.0.0
        run: |
          npm run dev &
          echo "Waiting for server to start..."
          for i in {1..30}; do
            if curl -s http://127.0.0.1:3000/api/pokemon/types > /dev/null; then
              echo "Server is ready!"
              break
            fi
            if [ $i -eq 30 ]; then
              echo "Server failed to start"
              exit 1
            fi
            sleep 1
          done

      - name: Run Backend Tests
        env:
          NODE_ENV: test
          PORT: 3000
          CI: true
          HOST: 127.0.0.1
          API_URL: http://127.0.0.1:3000
        run: npm test

      - name: Install Frontend Dependencies
        working-directory: ./frontend
        run: npm install

      - name: Run Frontend Tests
        working-directory: ./frontend
        env:
          NODE_ENV: test
          CI: true
        run: npm test

      - name: Install Vercel CLI
        run: npm install -g vercel

      - name: Deploy Backend
        env:
          VERCEL_TOKEN: ${{ secrets.VERCEL_TOKEN }}
          VERCEL_ORG_ID: ${{ secrets.VERCEL_ORG_ID }}
          VERCEL_PROJECT_ID: ${{ secrets.VERCEL_PROJECT_ID }}
        run: vercel --prod --token=${{ secrets.VERCEL_TOKEN }} --yes

      - name: Deploy Frontend
        working-directory: ./frontend
        env:
          VERCEL_TOKEN: ${{ secrets.VERCEL_TOKEN }}
          VERCEL_ORG_ID: ${{ secrets.VERCEL_ORG_ID }}
          VERCEL_PROJECT_ID: ${{ secrets.VERCEL_PROJECT_ID }}
          VITE_API_URL: ${{ secrets.VITE_API_URL }}
        run: vercel --prod --token=${{ secrets.VERCEL_TOKEN }} --yes
